---
# tasks file for imagemagick

- name: Remove apt package
  become: yes
  apt:
    pkg: imagemagick
    state: absent

- name: Check imagemagick is installed
  become: yes
  stat:
    path: "{{ imagemagick_install_dest }}/{{ imagemagick_command_name }}"
  register: cmd

- block:
    - name: Add repository
      become: yes
      apt_repository:
        filename: imagemagick.list
        repo: deb-src http://jp.archive.ubuntu.com/ubuntu/ xenial main restricted
        state: present

    - name: Install dependencies packages
      become: yes
      apt:
        pkg: "{{ item }}"
        update_cache: yes
      with_items: "{{ imagemagick_dependencies }}"

    - block:
        - name: Download WebP
          become: yes
          unarchive:
            src: "{{ imagemagick_webp_download_url }}"
            dest: "{{ imagemagick_webp_download_dest }}"
            remote_src: true

        - name: Install WebP
          become: yes
          shell: "creates={{ imagemagick_webp_download_dest }}/{{ imagemagick_webp_dirname }}/lib/{{ item }} cp -rf {{ imagemagick_webp_download_dest }}/{{ imagemagick_webp_dirname }}/lib/{{ item }} {{ imagemagick_webp_install_dest }}/lib/{{ item }}"
          with_items: "{{ imagemagick_webp_libs }}"
      when: imagemagick_webp_install

    - name: Install the build dependencies
      become: yes
      apt:
        pkg: imagemagick
        state: build-dep
        update_cache: yes

    - name: Download source code
      become: yes
      unarchive:
        src: "{{ imagemagick_download_url }}"
        dest: "{{ imagemagick_download_dest }}"
        remote_src: true
        creates: ImageMagick

    - name: configure,build,install and check
      become: yes
      command: "{{ item }}"
      args:
        chdir: "{{ imagemagick_download_dest }}/{{ imagemagick_dirname }}"
      with_items:
        - ./configure
        - make
        - make install
        - "ldconfig {{ imagemagick_ldconfig_path }}"
        # - make check

  when: not cmd.stat.exists
