---
# tasks/main.yml (imagemagick)
# Prefix : imagemagick

- name: Pre-check variables
  import_tasks: pre_check.yml
  tags: ["pre_check"]

- name: Install tasks
  import_tasks: install.yml
  when:
    - imagemagick_install_flag | bool
  tags: ["install"]
