---
# tasks/pre_check.yml (imagemagick)
# Prefix : imagemagick

- name: Check for deleted variables
  shell: >-
    echo "[WARNING]: 以下の変数は削除されました. 以下の URL を確認してください. @y_hashida";
    echo "    https://github.com/link-u/ansible-roles-v2_imagemagick/blob/master/README.md#削除された変数の一覧";

    {% if imagemagick_command_name is defined %}
      echo "imagemagick_command_name";
    {% endif %}

    {% if imagemagick_dirname is defined %}
      echo "imagemagick_dirname";
    {% endif %}

    {% if imagemagick_dependencies is defined %}
      echo "imagemagick_dependencies";
    {% endif %}

    {% if imagemagick_download_dest is defined %}
      echo "imagemagick_download_dest";
    {% endif %}

    {% if imagemagick_install_dest is defined %}
      echo "imagemagick_install_dest";
    {% endif %}

    {% if imagemagick_ldconfig_path is defined %}
      echo "imagemagick_ldconfig_path";
    {% endif %}

  register: __imagemagick_check_deleted_vars
  check_mode: no
  changed_when:
    - (__imagemagick_check_deleted_vars.stdout_lines | length) != 2
  notify: "Print warning for imagemagick (Check for deleted variables)"
